export enum ACCOUNT_TYPE {
  PERSONAL = "PERSONAL",
  ORGANISATION = "ORGANISATION",
}

export enum EVENT_INFO {
  SINGLE_EVENT = "SINGLE_EVENT",
  RECURRING_EVENT = "RECURRING_EVENT",
}

export enum TICKET_TYPE {
  PAID = "PAID",
  FREE = "FREE",
}
